---
simSeed: 10
simNumThreads: 15
simTakeSnapshots: true
envWidth: 3000
envHeight: 2000
envGroundLevel: 1200
envNumWarmupTicks: 1000
envTicksPerGeneration: 1000
envSpontaneousTreesPerGen: 200
particleRainBasePower: -50000
particleRainPowerChangePerTick: 55
particleSunBasePower: 70000
particleSunPowerChangePerTick: -45
fitnessRootNutrientCollectionPerSize: 3.0
fitnessRootNutrientCollectionPerDepth: 0.03
fitnessStructDecayPerSize: 1
fitnessActiveNodeDecayPerSize: 2
fitnessInactiveNodeDecayPerSize: 10
fitnessGainPerPowerAndNutrient: 2
fitnessRequirementPerChildPerNode: 5000
constantNodeMinimumSize: 10
constantNodeMinimumDistance: 40.0
mutationTreeBaseChance: 0.3
mutationChanceNodeType: 0.15
mutationChanceNodeSize: 0.3
mutationChanceNodeAngle: 0.25
mutationChanceNodeDistance: 0.15
mutationChanceNodeAddition: 0.3
mutationChanceNodeDeletion: 0.1
